name: Node.js CI

on:
  push:
    branches: [ new-feature-branch ]
  pull_request:
    branches: [ new-feature-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Start HTTP server
      run: npx http-server ./ -p 8080 &
      working-directory: . # Убедитесь, что это корректный путь к вашему index.html

    - name: Wait for HTTP server to start
      run: sleep 5

    - name: Check permissions
      run: ls -l ./node_modules/.bin

    - name: Grant execute permissions to Jest
      run: chmod +x ./node_modules/.bin/jest

    - name: Run tests
      run: npm test
